### PR TITLE
Fixed all of the grammar mistakes.

### PR DESCRIPTION
**Pull request by Turbine1991**

### CODE REVIEW

**Comment by thelastpenguin** [comment]
@Turbine1991 haha. Thanks :)

**Comment by thelastpenguin** [comment]
@Turbine1991 this project is looking for a new home, if you would be interested I can give you my contact details on steam and can work with you to pick up the project.

**Comment by Nuyek** [comment]
@thelastpenguin Hello, is this project still looking for a new home? I would be interested. Thank you.

**Comment by thelastpenguin** [comment]
@zombiezach8 yes it is! Please add me on steam: https://steamcommunity.com/id/thelastpenguin-dev 

And comment to let me know it’s you.
Glad to see interest! I’ll be happy to provide help understanding the code base and hopefully getting it running. 

It is certainly not for the faint of heart.

**Pull request merged**
